version: '3.8'

services:

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml
      - ./loki/index:/loki/index
      - ./loki/chunks:/loki/chunks
      - ./loki/cache:/loki/cache
    command: -config.file=/etc/loki/local-config.yaml


  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.84.0
    command: --config=/etc/otel/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    depends_on:
      - loki
    restart: unless-stopped
